### ISSUE TITLE
Make it optional to enable the CDN

### ISSUE THREAD

**Issue by jeffwhelpley** [rtgibbons/grunt-cloudfiles#14]
The current plugin will enable the CDN (i.e. make it public) if it is private. I don't think this is a good default behavior in general and I actually specifically need it to just leave the container private. Can we at the very least add an override option so that you can keep the container private? I don't mind writing this code if you don't have time, but please let me know what you think.

**Comment by rtgibbons** [comment]
This makes sense. Should be a simple control statement around https://github.com/rtgibbons/grunt-cloudfiles/blob/master/tasks/cloudfiles.js#L146 , I'd probably rename the function also to make it more accurate.

We can make the default to enable the CDN bit, but have an option to disable that way we don't change backwards compatibility.

**Comment by jeffwhelpley** [comment]
Just submitted a pull request. Let me know if you have any questions.

**Comment by rtgibbons** [comment]
Sorry for the delay, I've we just moved, and I'm just now getting caught up. I'm going to go ahead and close this one use the PR #15  to any other correspondence
