### ISSUE TITLE
authUrl for London no longer correct in Readme

### ISSUE THREAD

**Issue by hoffin** [rtgibbons/grunt-cloudfiles#16]
This took a while to get working as the authUrl in the readme is not longer correct. The correct value should be https://lon.identity.api.rackspacecloud.com/

This is working for me

prod: {
        'user': process.env.RACKSPACE_USERNAME,
        'key': process.env.RACKSPACE_API_KEY,
        'region': 'LON',
        'authUrl': 'https://lon.identity.api.rackspacecloud.com',
        'upload': [{
           ..

**Comment by rtgibbons** [comment]
Thanks, I'll merge in the resuest #17
