### ISSUE TITLE
Region setting doesn't work.

### ISSUE THREAD

**Issue by azhang** [rtgibbons/grunt-cloudfiles#18]
I set my region as `ORD` and it created/uploaded the files to DFW.

**Comment by rtgibbons** [comment]
We just pass this along to the pkgcloud , which version of pkgcloud do you have? `npm list pkgcloud`

Try update it to make sure you have the latest version? I'll look more on my end also.

**Comment by azhang** [comment]
I have pkgcloud 0.8.14. The region setting works when I use pkgcloud directly in my own code. I'll try looking around.

**Comment by azhang** [comment]
Oh! It's because I have region in `config.upload.region` rather than `config.region`. Thanks for the help!
