### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by tkellen** [rtgibbons/grunt-cloudfiles#2]
registerHelpers will be depreciated in grunt 0.4.

To see how helpers will be handled in the future (using standard npm require), check out the following links:
https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js#L15
https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/min.js

**Comment by rtgibbons** [comment]
Thanks for the heads up I forgot Ben isn't doing development in Master and the docs there are out of date.

I'll leave it open as a reminder down the road to switch it out.
