### ISSUE TITLE
Please upgrade your version of pkgcloud in package.json

### ISSUE THREAD

**Issue by emberdart** [rtgibbons/grunt-cloudfiles#24]
Hi!
The 0.8.14 version of pkgcloud you require has a bug in that if not all the regions exist for a certain endpoint then the application breaks with a "Unable to identify target endpoint for Service: cloudBigData" error.

I was trying to upload to IAD Cloud Files but the iteration upstream actually crashed since there was no IAD endpoint for Cloud Big Data.

The bug has now been fixed upstream, so I've updated my copy of your repository to use the latest version and it's fine for uploading to IAD Cloud Files now (but not sure about the rest).

So please update your package.json if the new version works.
Cheers

**Comment by rtgibbons** [comment]
Thanks, i've pushed v0.3 as using ~0.9.4
