### ISSUE TITLE
Wrong versions available?

### ISSUE THREAD

**Issue by emberdart** [rtgibbons/grunt-cloudfiles#30]
Hi,
I just tried to use version 0.1.1 but npm says only versions are  ["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.2.1","0.3.0"]

What gives? Has someone stolen the name?

Cheers

**Comment by rtgibbons** [comment]
Changelog is out of date. It should of read 0.2.1 but since then 0.3.0 has been published.

https://www.npmjs.com/package/grunt-cloudfiles
