### ISSUE TITLE
Usage examples required

### ISSUE THREAD

**Issue by adilwali** [rtgibbons/grunt-cloudfiles#4]
This plugin looks fantastic and like exactly what I need!  

I'm going to dive into the source now to better figure out how to use it.  If I can get it working properly, I'll happily add some usage examples to the README.  

In the meanwhile, if anyone else has some basic examples, that'd help a lot.

**Comment by rtgibbons** [comment]
Here's an example use 0.0.3, a small snippet from Gruntfile.js

```
var VERSION = grunt.template.today('yyyymmddHHMMssl');
cloudfiles: {
      stage: {
        'user': '<user>',
        'key': '<api_key>',
        'upload': [{
          'container': 'my_container_stage',
          'src': 'source/static/**/*',
          'dest': 'some/folder/' + VERSION + '/',
          'stripcomponents': 1
        }]
      },
      prod: {
        'user': '<user>',
        'key': '<api_key>',
        'upload': [{
          'container': 'my_container_prod',
          'src': 'source/static/**/*',
          'dest': 'some/folder/' + VERSION + '/',
          'stripcomponents': 1
        }]
      }
    },
```

**Comment by rtgibbons** [comment]
btw, `stripcomponent` is the command from tar, it 'strip NUMBER leading components from file names on extraction' where component == folders.

So for example the file `source/static/js/app/main.js` would go into the container in folder `some/folder/20130224100822357/static/js/app/main.js`

**Comment by adilwali** [comment]
awesome!  Thanks so much.  I'll update the readme and throw in a pull request.
